add_newline = false
palette= 'amethyst'
# ─── Palette ─────────────────────────────────────────────────
[palettes.amethyst]
accent = "#7766FF"
bg     = "#04040A"
fg     = "#C8B8FF"
dark   = "#2A1B5E"
mid    = "#3D2B8A"
error  = "#FF4466"

# ─── Format ──────────────────────────────────────────────────

format = """
  $os\
  $directory\
  $git_branch$git_commit$git_state $git_status\
  $c\
  $cpp\
  $java\
  $python\
  $rust\
  $nodejs\
  $custom\
  $status\
  $character\n
"""

continuation_prompt = '▶▶ '

# ─── Operating System ────────────────────────────────────────
[os]
disabled = false
format = "[$symbol ](bold fg:accent)"

[os.symbols]
Fedora = " "

# ─── Directory ───────────────────────────────────────────────
[directory]
disabled = false
format = "[$path](bold fg:fg)"
truncate_to_repo = false
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Pictures"  = "󱢉 "
"Music"     = " "

# ─── Git ─────────────────────────────────────────────────────
[git_branch]
format = " [  $branch](fg:#9198a1)"

[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
format = '[[( $all_status$ahead_behind )](fg:#769ff0)]($style)'
style = "bg:#394260"

# ─── Character ───────────────────────────────────────────────
[character]
success_symbol = "[❯](bold fg:accent)"
error_symbol   = "[❯](bold fg:error)"

# ─── Languages ───────────────────────────────────────────────
[c]
format = " [$symbol]($style)"
style = "bold fg:fg"
symbol = " "
detect_extensions = ["c", "h"]

[cpp]
format = " [$symbol]($style)"
style = "bold fg:fg"
symbol = " "
detect_extensions = ["cpp", "hpp", "cc", "cxx"]

[java]
format = " [$symbol]($style)"
style = "bold fg:fg"
symbol = " "

[python]
format = " [$symbol($virtualenv)]($style)"
style = "bold fg:fg"
symbol = " "
version_format = "${raw}"

[rust]
format = " [$symbol]($style)"
style = "bold fg:fg"
symbol = " "

[nodejs]
format = " [$symbol]($style)"
style = "bold fg:fg"
symbol = "󰎙 "
detect_extensions = ["js", "mjs", "cjs", "ts"]
detect_files = ["package.json", "package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]
version_format = "${raw}"

