music_directory    "~/Music"
playlist_directory "~/.local/share/chezmoi/dot_config/mpd/playlists"
db_file            "~/.local/share/chezmoi/dot_config/mpd/database"
log_file           "~/.config/mpd/log"
pid_file           "~/.config/mpd/pid"
state_file         "~/.config/mpd/state"

audio_output {
    type "pipewire"
    name "PipeWire Output"
}

bind_to_address "127.0.0.1"
port            "6600"
