[data]
    theme = "amethyst"
    wallpaper = "lain2.png"
    name = "KaxuTheSheep"

[data.colors]
    background = "#04040A"
    foreground = "#C8B8FF"
    cursor     = "#7766FF"
    color0  = "#04040A"
    color1  = "#5268AC"
    color2  = "#BF00FF"
    color3  = "#7766FF"
    color4  = "#B498E9"
    color5  = "#D354A1"
    color6  = "#5F8FD0"
    color7  = "#C8B8FF"
    color8  = "#2A2A4A"
    color9  = "#6478BC"
    color10 = "#8A2882"
    color11 = "#8877FF"
    color12 = "#3C0061"
    color13 = "#E364B1"
    color14 = "#86B4EA"
    color15 = "#E8D8FF"
