##############################
### WINDOWS AND WORKSPACES ###
##############################

# Layer Rules
# Window Rules
windowrule = suppressevent maximize, class:.*
windowrule = nofocus, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0

windowrule = float, class:^(pavucontrol)$
windowrule = center, class:^(pavucontrol)$

windowrule = float, class:^(Bitwarden)$
windowrule = center, class:^(Bitwarden)$

windowrule = float, class:^(waypaper)$
windowrule = center, class:^(waypaper)$
windowrule = size 900 350, class:^(waypaper)$
