##############################
### WINDOWS AND WORKSPACES ###
##############################

# Layer Rules
layerrule = blur, namespace:rofi
layerrule = ignorezero, namespace:rofi
layerrule = xray 0, namespace:rofi

# Window Rules
windowrule = suppressevent maximize, class:.*
windowrule = nofocus, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0
windowrule = float, class:^(Bitwarden)$
windowrule = float, class:^(pavucontrol)$
windowrule = center, class:^(Bitwarden)$
windowrule = center, class:^(pavucontrol)$
